version: '3.8'

services:
  discovery-service:
    image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER:-latest}
    container_name: ${CONTAINER_NAME:-discovery-service}
    ports:
      - "${PORT:-8190}:${PORT:-8190}" # Default to 8190 if PORT is not set
    env_file:
      - ./.env
    networks:
      - demo-network
    restart: unless-stopped

networks:
  demo-network:
    driver: bridge