server:
  port: ${PORT:8190} # Default to 8190 if PORT is not set

spring:
  application:
    name: ${SPRING_APP_NAME:discovery-service} # Default name if not set
  config:
    import: optional:configserver:http://localhost:8190 # Optional Config Server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false    # Don't register itself
    fetch-registry: false          # Don't fetch registry
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF